version: '3.8'

services:
  transaction-db:
    image: postgres:15-alpine
    container_name: transaction-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction_db
    ports:
      - "5434:5432"
    volumes:
      - transaction_db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # port AMQP - ini yang dipakai service untuk publish/consume message
      - "15672:15672" # port dashboard management UI (buka lewat browser)

  transaction-service:
    build: .
    container_name: transaction-service
    restart: always
    depends_on:
      - transaction-db
      - rabbitmq
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@transaction-db:5432/transaction_db?schema=public"
      RABBITMQ_URL: "amqp://rabbitmq:5672"
      PORT: 3001
    ports:
      - "3001:3001"

volumes:
  transaction_db_data: