version: '3.8'

services:
  transaction-db:
    image: postgres:15-alpine
    container_name: simavek-transaction-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction_db
    ports:
      - "5434:5432"
    volumes:
      - transaction_db_data:/var/lib/postgresql/data
    networks:
      - simavek-network

  transaction-service:
    build: ./simavek-transaction-service
    container_name: simavek-transaction-service
    restart: always
    depends_on:
      - transaction-db
      - rabbitmq
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@transaction-db:5432/transaction_db?schema=public
      RABBITMQ_URL: amqp://rabbitmq:5672
      PORT: 3001
      HASURA_GRAPHQL_ENDPOINT: http://inventory-hasura:8080/v1/graphql
      HASURA_ADMIN_SECRET: myadminsecret
    networks:
      - simavek-network

volumes:
  transaction_db_data: